site_name: TANAP resources
repo_name: "globalise-huygens/tanap.docs.globalise.huygens.knaw.nl/"
repo_url: "https://github.com/globalise-huygens/tanap.docs.globalise.huygens.knaw.nl/"
site_url: "https://docs.globalise.huygens.knaw.nl/tanap/"

theme:
  name: material
  # logo: static/img/logo/globalise_g.svg
  favicon: static/img/logo/globalise_g.svg
  #icon:
  #  logo: material/flask
  features:
    # - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.path
    - navigation.top

nav:
  - Home: index.md
  - "TANAP Archival Inventories": archival-inventories/index.md
  - "TANAP Index and Establishment Reconstructions": tanap-index-establishment-reconstructions/index.md
  - "TANAP Cape of Good Hope Transcriptions": cape-transcriptions/index.md

markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - smarty
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.details
  - footnotes
plugins:
  - search # necessary for search to work
  - git-revision-date-localized
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/fuse.js@6.6.2/dist/fuse.min.js
  - javascripts/fuzzy-search.js
extra:
  generator: false

copyright: <p>
  <a rel="license" href="https://creativecommons.org/publicdomain/zero/1.0/"><img alt="Creative Commons License"
  style="border-width:0" src="https://licensebuttons.net/i/l/by-sa/transparent/ff/ff/ff/88x31.png" /></a><br/>
  <span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">TANAP Resources</span> offers a curated selection of materials that were previously available on the TANAP website. It has been developed by <a
  xmlns:cc="http://creativecommons.org/ns#" href="https://globalise.huygens.knaw.nl/" property="cc:attributionName"
  rel="cc:attributionURL">GLOBALISE</a>, a project based at the <a href="https://www.huygens.knaw.nl/">Huygens Institute</a> in Amsterdam and funded by the <a href="https://www.nwo.nl/en">Netherlands Organization for Scientific Research (NWO)</a>. The materials featured here were shared by the <a href="https://www.nationaalarchief.nl/">National Archives of the Netherlands</a>.
  <br>
  Information on this static website is licensed under a <a rel="license"
  href="https://creativecommons.org/publicdomain/zero/1.0/">CC0 License</a>.
  </p>
